services:
  graphdb:
    image: ontotext/graphdb:10.3.1
    container_name: graphdb
    ports:
      - "7200:7200"
    volumes:
      - ./graphdb-data:/opt/graphdb/home
      - ./graphdb-import:/opt/graphdb/import
    environment:
      - JAVA_OPTS=-Xms1g -Xmx2g